from firsttask import *

accounts = []
create_account(accounts, -1, 'jkfdbk', 5)
create_account(accounts, 1, 'jkfdbk', -5)
create_account(accounts, 1, 'jkfdbk', 5)
create_account(accounts, 1, 'jefr', 342423)
print(accounts)
create_account(accounts, 23, 'jkfdbk', 40)
print(accounts)
deposit(accounts, 2, 10)
deposit(accounts, 1, -12)
deposit(accounts, 1, 10)
print(accounts)
withdraw(accounts, 2, 10)
withdraw(accounts, 1, -10)
withdraw(accounts, 1, 100)
withdraw(accounts, 1, 10)
print(accounts)
transfer(accounts, -23, 1, 30)
transfer(accounts, 23, -2, 30)
transfer(accounts, 23, 1, -30)
transfer(accounts, 23, 1, 30000)
transfer(accounts, 23, 1, 30)
print(accounts)
get_balance(accounts, 2)
get_balance(accounts, 1)
get_balance(accounts, 23)
